"""
RLFS (Reinforcement Learning from Formal Systems) - Python Sandbox
==================================================================
This module provides a controlled environment to safely execute Python code 
generated by the SNAP-C1 model and capture the stdout/stderr.
The outputs are then fed back into the Core as an objective reward signal.
"""

import sys
import io
import traceback
import contextlib
import multiprocessing
from multiprocessing import Process, Queue
from loguru import logger
from typing import Tuple, Dict, Any

def _execute_code_worker(code_string: str, queue: Queue):
    """
    Sub-process worker that executes the code. 
    Isolated to prevent model-generated code from crashing the main training process
    or causing infinite loops.
    """
    # Create isolated string buffers for stdout and stderr
    stdout_buffer = io.StringIO()
    stderr_buffer = io.StringIO()
    
    # We create an empty dictionary to serve as the local execution namespace
    exec_namespace: Dict[str, Any] = {}
    
    try:
        # Redirect standard output and error to our buffers
        with contextlib.redirect_stdout(stdout_buffer), contextlib.redirect_stderr(stderr_buffer):
            # Execute the untrusted code string in the isolated namespace
            exec(code_string, {}, exec_namespace)
            
        success = True
        error_type = None
        error_message = None
        
    except Exception as e:
        success = False
        error_type = type(e).__name__
        # Capture the precise traceback to feed back into the model's memory
        error_message = "".join(traceback.format_exception(type(e), e, e.__traceback__))
        
    # Send the results back to the main process
    queue.put({
        "success": success,
        "stdout": stdout_buffer.getvalue(),
        "stderr": stderr_buffer.getvalue(),
        "error_type": error_type,
        "error_traceback": error_message,
        # We also return requested variables if the test asks for it
        # Note: only primitive variables can be safely pickled across process bounds
        "namespace_repr": {k: str(v) for k, v in exec_namespace.items() if not k.startswith('_')}
    })

class PythonSandbox:
    """Manages the execution of model-generated code with strict timeouts."""
    def __init__(self, timeout_seconds: int = 3):
        self.timeout = timeout_seconds
        
    def run(self, code_string: str) -> dict:
        """
        Executes the code string in an isolated sub-process with a timeout.
        
        Returns:
            dict: The execution results containing success status, stdout, and tracebacks.
        """
        queue = multiprocessing.Queue()
        
        # Spawn isolated execution process
        process = multiprocessing.Process(
            target=_execute_code_worker, 
            args=(code_string, queue)
        )
        process.start()
        
        # Wait for the process to finish or hit the timeout
        process.join(timeout=self.timeout)
        
        if process.is_alive():
            # The model wrote an infinite loop or hung process!
            logger.warning(f"Sandbox Timeout ({self.timeout}s): Model generated an infinite loop.")
            process.terminate()
            process.join() # Ensure cleanup
            
            return {
                "success": False,
                "stdout": "",
                "stderr": "",
                "error_type": "TimeoutError",
                "error_traceback": f"Execution exceeded maximum allowed time of {self.timeout} seconds.",
                "namespace_repr": {}
            }
            
        # Process completed normally, retrieve results
        if not queue.empty():
            return queue.get()
        else:
            return {
                "success": False,
                "error_type": "UnknownSandboxError",
                "error_traceback": "Process exited without returning data to the IPC queue."
            }

if __name__ == "__main__":
    # Test the sandbox environment
    print("\n--- Testing RLFS Python Sandbox ---\n")
    sandbox = PythonSandbox(timeout_seconds=2)
    
    # 1. Test Valid Code
    print("Testing Pass Condition:")
    good_code = """
def add(a, b):
    return a + b
result = add(5, 7)
print(f"The result is {result}")
"""
    
    res1 = sandbox.run(good_code)
    print(f"Success: {res1['success']} | Output: {res1['stdout'].strip()}")
    
    
    # 2. Test Syntax Error / Exception
    print("\nTesting Failure Condition (TypeError):")
    bad_code = """
print("Merging int and string")
x = 5 + "apple"
"""
    res2 = sandbox.run(bad_code)
    print(f"Success: {res2['success']} | Error Type: {res2['error_type']}")
    
    # 3. Test Infinite Loop (Timeout)
    print("\nTesting Timeout Condition (Infinite Loop):")
    loop_code = """
while True:
    pass
"""
    res3 = sandbox.run(loop_code)
    print(f"Success: {res3['success']} | Error Type: {res3['error_type']}")
    res3 = sandbox.run(loop_code)
    print(f"Success: {res3['success']} | Error Type: {res3['error_type']}")
