import ast
import torch
import torch.nn as nn
from loguru import logger
from typing import Dict, Any, List

class ASTRewardEvaluator:
    """
    SNAP-C1 V3 Model Component: Offline Formal Systems Evaluator
    
    This replaces `sandbox.py`. 
    Rather than relying on the Windows OS to execute Python subprocesses
    and wait 1.0 second for timeouts, this module parses the AST graph generated
    by the Neuromorphic Graph Decoder and instantly calculates the mathematical 
    "Edit Distance" against known Ground Truth ASTs.
    """
    
    def __init__(self, penalty_scale: float = 10.0):
        self.penalty_scale = penalty_scale
        
    def _parse_to_ast(self, code_string: str) -> ast.AST:
        """Attempts to parse raw strings into python Abstract Syntax Trees."""
        try:
            return ast.parse(code_string)
        except SyntaxError:
            return None
            
    def _get_node_count(self, tree: ast.AST) -> int:
        """Counts the total number of structural nodes in the AST."""
        if tree is None:
            return 0
        return sum(1 for _ in ast.walk(tree))
        
    def evaluate(self, generated_code: str, ground_truth_code: str) -> float:
        """
        Calculates the Formal Reward based entirely on mathematical tree structure
        without running any sub-processes.
        
        Args:
            generated_code: The prediction generated by the AI
            ground_truth_code: The valid solution from the dataset
            
        Returns:
            reward: Float value (-10.0 to 1.0). 
                    Negative for structural logic errors.
                    Positive for exact logical matches.
        """
        gen_ast = self._parse_to_ast(generated_code)
        target_ast = self._parse_to_ast(ground_truth_code)
        
        # 1. Total Failure: The model output invalid syntax that couldn't even form a tree
        if gen_ast is None:
            return -self.penalty_scale
            
        # 2. Extract Structural Signatures (Node Types only, ignoring variable names)
        # This allows the AI to use different variable names ('x' vs 'num') and still get rewarded
        gen_signature = [type(node).__name__ for node in ast.walk(gen_ast)]
        target_signature = [type(node).__name__ for node in ast.walk(target_ast)]
        
        # 3. Calculate "Tree Edit Distance" (Simplified Jaccard Similarity for Speed)
        # In a full C++ V3 engine, this would use a strict Levenshtein Tree Distance algorithm.
        intersection = len(set(gen_signature).intersection(set(target_signature)))
        union = len(set(gen_signature).union(set(target_signature)))
        
        iou = intersection / max(union, 1) # Range 0.0 to 1.0
        
        # 4. Map the logical overlap to the Reward space
        if iou == 1.0:
            # Structurally perfect code!
            logger.debug("OFLINE AST MATCH: Syntactic graph matches Ground Truth perfectly. (+1.0)")
            return 1.0
            
        elif iou > 0.5:
            # Getting closer, but mathematically flawed logic loops
            penalty = self.penalty_scale * (1.0 - iou)
            logger.debug(f"OFFLINE AST MISMATCH: Logic mostly valid, but structurally misaligned. Penalty: -{penalty:.2f}")
            return -penalty
            
        else:
            # Completely hallucinated logic tree
            logger.debug(f"OFFLINE AST HALLUCINATION: Graph structure completely invalid. Penalty: -{self.penalty_scale}")
            return -self.penalty_scale

if __name__ == "__main__":
    print("\n--- Testing V3 Offline AST Formal Systems Evaluator ---")
    evaluator = ASTRewardEvaluator()
    
    target_code = """
def multiply(a, b):
    return a * b
"""
    
    # 1. Test Syntax Error (Should equal -10.0 instantly without crashing Windows)
    bad_code = "def multiplya, b"
    reward = evaluator.evaluate(bad_code, target_code)
    print(f"\nCondition 1: Flat Syntax Error")
    print(f"Generated Code: '{bad_code}'")
    print(f"Instant AST Reward: {reward}")
    
    # 2. Test Invalid Logic Shape (Should calculate Edit Distance instantly)
    bad_logic = """
def multiply(a, b):
    print(a)
    print(b)
"""
    reward = evaluator.evaluate(bad_logic, target_code)
    print(f"\nCondition 2: Valid Syntax, Incorrect Mathematical Logic")
    print(f"Instant AST Reward: {reward}")
    
    # 3. Test Valid Shape (Different Variables)
    good_code = """
def get_product(x, y):
    return x * y
"""
    reward = evaluator.evaluate(good_code, target_code)
    print(f"\nCondition 3: Valid Mathematical Shape (Different Variable Names)")
    print(f"Instant AST Reward: {reward}")
    
    print("\nOffline V3 Evaluator is ready. No sub-process spawning required.")
